/**
 * This file is auto-generated by Supabase CLI.
 * Run `npm run db:types` to regenerate this file after schema changes.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          preferences: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          username?: string | null
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey"
            columns: ["id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      dialog_sessions: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          metadata: Json
          default_model: string | null
          default_temperature: number | null
          default_max_tokens: number | null
          is_pinned: boolean
          last_activity_at: string
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title?: string
          description?: string | null
          metadata?: Json
          default_model?: string | null
          default_temperature?: number | null
          default_max_tokens?: number | null
          is_pinned?: boolean
          last_activity_at?: string
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string | null
          metadata?: Json
          default_model?: string | null
          default_temperature?: number | null
          default_max_tokens?: number | null
          is_pinned?: boolean
          last_activity_at?: string
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "dialog_sessions_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      conversation_nodes: {
        Row: {
          id: string
          session_id: string
          user_id: string
          parent_id: string | null
          role: string
          content: string | null
          content_type: string
          depth: number
          sequence_order: number
          model_name: string | null
          model_provider: string | null
          temperature: number | null
          max_tokens: number | null
          is_streaming: boolean
          streaming_complete: boolean
          stream_error: string | null
          prompt_tokens: number | null
          completion_tokens: number | null
          total_tokens: number | null
          metadata: Json
          generation_started_at: string | null
          generation_completed_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          parent_id?: string | null
          role: string
          content?: string | null
          content_type?: string
          depth?: number
          sequence_order?: number
          model_name?: string | null
          model_provider?: string | null
          temperature?: number | null
          max_tokens?: number | null
          is_streaming?: boolean
          streaming_complete?: boolean
          stream_error?: string | null
          prompt_tokens?: number | null
          completion_tokens?: number | null
          total_tokens?: number | null
          metadata?: Json
          generation_started_at?: string | null
          generation_completed_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          parent_id?: string | null
          role?: string
          content?: string | null
          content_type?: string
          depth?: number
          sequence_order?: number
          model_name?: string | null
          model_provider?: string | null
          temperature?: number | null
          max_tokens?: number | null
          is_streaming?: boolean
          streaming_complete?: boolean
          stream_error?: string | null
          prompt_tokens?: number | null
          completion_tokens?: number | null
          total_tokens?: number | null
          metadata?: Json
          generation_started_at?: string | null
          generation_completed_at?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversation_nodes_session_id_fkey"
            columns: ["session_id"]
            referencedRelation: "dialog_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_nodes_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_nodes_parent_id_fkey"
            columns: ["parent_id"]
            referencedRelation: "conversation_nodes"
            referencedColumns: ["id"]
          }
        ]
      }
      branch_options: {
        Row: {
          id: string
          session_id: string
          parent_node_id: string
          child_node_id: string
          branch_name: string | null
          branch_description: string | null
          is_active: boolean
          selection_count: number
          metadata: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          session_id: string
          parent_node_id: string
          child_node_id: string
          branch_name?: string | null
          branch_description?: string | null
          is_active?: boolean
          selection_count?: number
          metadata?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          parent_node_id?: string
          child_node_id?: string
          branch_name?: string | null
          branch_description?: string | null
          is_active?: boolean
          selection_count?: number
          metadata?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "branch_options_session_id_fkey"
            columns: ["session_id"]
            referencedRelation: "dialog_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "branch_options_parent_node_id_fkey"
            columns: ["parent_node_id"]
            referencedRelation: "conversation_nodes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "branch_options_child_node_id_fkey"
            columns: ["child_node_id"]
            referencedRelation: "conversation_nodes"
            referencedColumns: ["id"]
          }
        ]
      }
      node_paths: {
        Row: {
          ancestor_id: string
          descendant_id: string
          depth: number
          created_at: string
        }
        Insert: {
          ancestor_id: string
          descendant_id: string
          depth?: number
          created_at?: string
        }
        Update: {
          ancestor_id?: string
          descendant_id?: string
          depth?: number
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "node_paths_ancestor_id_fkey"
            columns: ["ancestor_id"]
            referencedRelation: "conversation_nodes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "node_paths_descendant_id_fkey"
            columns: ["descendant_id"]
            referencedRelation: "conversation_nodes"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      active_conversation_paths: {
        Row: {
          id: string | null
          session_id: string | null
          user_id: string | null
          parent_id: string | null
          role: string | null
          content: string | null
          depth: number | null
          sequence_order: number | null
          model_name: string | null
          is_streaming: boolean | null
          streaming_complete: boolean | null
          created_at: string | null
          session_title: string | null
          ancestor_path: string[] | null
        }
        Insert: never
        Update: never
        Relationships: []
      }
      session_statistics: {
        Row: {
          session_id: string | null
          user_id: string | null
          title: string | null
          last_activity_at: string | null
          created_at: string | null
          total_nodes: number | null
          user_messages: number | null
          assistant_messages: number | null
          total_tokens_used: number | null
          max_depth: number | null
          branch_points: number | null
        }
        Insert: never
        Update: never
        Relationships: []
      }
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
